# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update foodbanks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight UTC (8am MYT)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: production
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv googlemaps openpyxl
    - name: execute py script
      env:
        GMAPS_GEOCODING_API_KEY: ${{ secrets.GMAPS_GEOCODING_API_KEY }}
      run: python3 update_foodbanks.py 1Pd5ceJ4uDwt85h4Krf94QL6sfF-CaUCmDC1atMspOqg src/screens/FoodBanks/foodbanks.json
    - name: commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "update foodbanks.json" -a
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: production
